name: greengrocer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.4.0
  badges: ^3.0.2
  intl: ^0.18.1
  add_to_cart_animation: ^0.0.7
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0
  get: ^4.6.5
  dio: ^5.2.0+1
  json_annotation: ^4.8.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  flutter_secure_storage: ^8.0.0
  clipboard: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_images/app_icon.png"
  remove_alpha_ios: true
# flutter pub run flutter_launcher_icons

