name: greengrocer
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.4.0
  badges: ^3.0.2
  intl: ^0.18.0
  qr_flutter: ^4.0.0
  add_to_cart_animation: ^0.0.7
  fluttertoast: ^8.1.2
  flutter_launcher_icons: ^0.11.0
  shimmer: ^2.0.0
  get: ^4.6.5
  dio: ^5.0.0
  json_annotation: ^4.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  # flutter pub run build_runner build
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_images/app_icon.png"
  remove_alpha_ios: true
# flutter pub run flutter_launcher_icons
